### ISSUE TITLE
API possibly down?

### ISSUE THREAD

**Issue by bvasilop** [2016rshah/githubchart-api#11]
I've been using your HTMl Github calendar embed for a few months now. It's been working great except it's down for some reason today. Was wondering if any changes have been made to cause it to not fetch anymore.

**Comment by bvasilop** [comment]
It's back up an running. Thanks again for this useful embed.

**Comment by 2016rshah** [comment]
Mea culpa, I accidentally let my domain name expire!

**Comment by bvasilop** [comment]
Hmmm. Was working for a half hour or so and went down again... Wonder if the domain is still inactive?

**Comment by bvasilop** [comment]
Ok..It's back up again. Think it's all sorted out. Thanks again.
