### ISSUE TITLE
Making it mobile optimised

### ISSUE THREAD

**Issue by nikhilmufc7** [2016rshah/githubchart-api#12]
Hi Great work on this , I was looking for a way to make it mobile optimised , is there a way to do that?

**Comment by 2016rshah** [comment]
The API serves an SVG image, which stands for scalable vector graphic. That means you can already make the image as large or small as you would like on any device (with CSS, etc.)! 

If you want an example feel free to check out how I did it [here](https://www.rshah.org/) from [the source code](https://github.com/2016rshah/2016rshah.github.io).

Good luck!
