### ISSUE TITLE
Doesn't show color for 1 contribution

### ISSUE THREAD

**Issue by nickBlack4** [2016rshah/githubchart-api#17]
I have a day that I only had one contribution when I forked another repository.  The color is not showing up on the graph and so it shows as a day with zero contributions.  I'm assuming this is a bug?

This can be seen on nickblackcode.com and my github is github.com/nickblack4

The day is March 1st that has one contribution not showing up on graph.

Cheers

**Comment by 2016rshah** [comment]
This may be a problem with the underlying ruby gem, so I would raise this issue there instead:  https://github.com/akerl/githubchart
