### ISSUE TITLE
API is down? Internal Server Error

### ISSUE THREAD

**Issue by Jfaler** [2016rshah/githubchart-api#22]
Thanks for taking the time to build this beautiful project. I've been using this to display my chart for over a year but now it says internal server error https://ghchart.rshah.org/0E2F44/jfaler

**Comment by 2016rshah** [comment]
Good question! I haven't changed anything, but I'm looking into it now to see what the problem is. I'll keep y'all updated.

**Comment by 2016rshah** [comment]
I (re)opened an issue with the underlying gem, if anybody wants to follow along with what is happening there: https://github.com/akerl/githubchart/issues/44

**Comment by Jfaler** [comment]
It works! Thank you so much.

**Comment by 2016rshah** [comment]
Should be fixed with https://github.com/2016rshah/githubchart-api/commit/c9b06792f806027a016af032de7a583acd9e518d thanks to @akerl!
