### ISSUE TITLE
Automatically refresh

### ISSUE THREAD

**Issue by crydotsnake** [2016rshah/githubchart-api#26]
Hello,

very cool API! But does the image also refreshing automatically after a couple of times? So in case my stats have been changed.

Thanks!

**Comment by 2016rshah** [comment]
This tool will automatically refresh, but the page you're viewing your chart on might be caching the image. Try doing a hard refresh of the page (Command + Shift + R for Chrome on Mac) and see if that fixes your problem

**Comment by crydotsnake** [comment]
Thanks ! :)
