### ISSUE TITLE
Free hosting expiring 11/28/22 😬 

### ISSUE THREAD

**Issue by 2016rshah** [2016rshah/githubchart-api#28]
This project is currently hosted on the free tier of heroku. Heroku recently sent me an email saying 

> Starting November 28, 2022, free Heroku Dynos, free Heroku Postgres, and free Heroku Data for Redis® will no longer be available.

Ideally I would like to not have to pay for this project out of pocket. If anyone has any recommendations for switching hosts or would be interested in setting that up, please reach out !!!

**Comment by carlalexander** [comment]
Sorry, I'm not familiar with Ruby hosting. Fly.io has a [free tier](https://fly.io/docs/about/pricing/) that might work. What are the usage stats for the app?

**Comment by ThePlugJumbo** [comment]
I would be more than happy to host this project on a Heroku paid dyno.

**Comment by 2016rshah** [comment]
Used the student developer pack to get free credits for a year, so fixed for now !!!
