### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by tripflex** [2016rshah/githubchart-api#3]
Looks like i'm getting an internal server error when attempting to generate an SVG for my username:

http://ghchart.rshah.org/tripflex

I modified an Ubersicht widget to use your API but maybe due to the amount of requests it makes to your server, or graphs that were generated, maybe that caused the 500 internal server error?

https://github.com/cobyism/ubersicht-github/issues/7

**Comment by tripflex** [comment]
Of course right after I post this it works just fine ... dunno what was causing it

![](https://smyl.es/img/Screenshot_2016-05-31_01-56-29_PM.png)

**Comment by 2016rshah** [comment]
This has happened to me before as well. As I was looking into what was happening the error fixed itself. I suspect it has something to do with my hosting on Heroku, but it hasn't been a consistent enough bug to motivate me to hunt down the error and I don't even know how I would start trying to do so. I'm glad everything is working for you now, though!
