### ISSUE TITLE
Image is broken with "Internal Server Error"

### ISSUE THREAD

**Issue by atrinh0** [2016rshah/githubchart-api#33]
<img width="824" alt="Screenshot 2023-07-15 at 10 21 15" src="https://github.com/2016rshah/githubchart-api/assets/16542463/5ac75e9d-3956-4d7c-85f8-9f1f6891b242">

**Comment by abukhi148** [comment]
Repo tracker and other libraries that fetch data using the GitHub contributions API are not working as well. GitHub probably made some changes to the API.

https://repo-tracker.com/r/gh/nuxt/nuxt

**Comment by scottwmaxwell** [comment]
Any chance the changes of the Github contributions API that impact this can be identified?
I would try myself, but I have no experience with this API.

**Comment by abukhi148** [comment]
With the updated dependencies in #35, it should be working again.

**Comment by 2016rshah** [comment]
Fixed by https://github.com/2016rshah/githubchart-api/commit/639b3ff4570126d128c287a53ab79c652f012072
