### ISSUE TITLE
You need a TLS cert on your website.

### ISSUE THREAD

**Issue by pgporada** [2016rshah/githubchart-api#5]
I want to use your include code, but your site doesn't use TLS. You should use[ Let's Encrypt](https://letsencrypt.org/) to do this for free!

Specifically on your server you can use [certbot](https://certbot.eff.org/) from the [EFF](https://www.eff.org/).

**Comment by 2016rshah** [comment]
I am hosting this project on a free Heroku dyno. Since Heroku is a PaaS I have to pay money to enable the [SSL endpoint](https://devcenter.heroku.com/articles/ssl) and upload a certificate. Therefore unfortunately I do not plan to enable TLS/SSL anytime soon, but I appreciate the suggestion!

**Comment by GeorgeWL** [comment]
SSL via cloudfront CDN?

Works for github pages with custom domains. I've yet to test with Heroku, but it might work in a similar method.

**Comment by GeorgeWL** [comment]
https://robots.thoughtbot.com/set-up-cloudflare-free-ssl-on-heroku 

try this out maybe @2016rshah ?

it seems to work for a lot of other users of the free tier of Heroku.

**Comment by 2016rshah** [comment]
That actually looks pretty good I will look into it!

It seems kind of like a work around based on:

> If a user inspects certificate information, they will not see your domain name in the common name section. Your domain name will instead appear in DNS Name Section.
> Those caveats are probably fine for staging website. However, it may not be appropriate in production. In that case, you can actually tell CloudFlare to bypass the traffic, and you need to point your DNS record to Heroku SSL endpoint.

but I think I'm probably fine with that since it is free

**Comment by byronpolley** [comment]
+1. I am getting a mixed content warning too and my personal website doesn't look as good. Could you possibly explain how I would configure this to run on Google firebase so I can host it myself?

**Comment by 2016rshah** [comment]
Okay, I have set up HTTPS on cloudflare as per the guide! I'm not super familiar with SSL, though, so I am not sure if the steps in the guide are sufficient. Are there any further steps I need to take for everything to work correctly for you guys?

**Comment by byronpolley** [comment]
@2016rshah You're a gem my guy, thanks you can close.
