### ISSUE TITLE
Feature Request: "XXX contributions this year" as part of image.

### ISSUE THREAD

**Issue by GeorgeWL** [2016rshah/githubchart-api#6]
Is it possible to put in a variable in the link to make it show the

"XXX contributions this year" 
![image](https://user-images.githubusercontent.com/5931248/26836790-b67f2c82-4ad3-11e7-8104-94e54a443bd3.png)

part that's on the github chart?

so instead of http://ghchart.rshah.org/GeorgeWL the option to use http://ghchart.rshah.org/GeorgeWL/variant

or something like that?

**Comment by 2016rshah** [comment]
This seems like a really cool idea! If you can work something like that out with [this Ruby gem](https://github.com/akerl/githubchart) I'll totally include it! Open up an issue on that repo and keep me updated. Until then I'm gonna close this issue
