### ISSUE TITLE
Add caching headers

### ISSUE THREAD

**Issue by Michael-F-Bryan** [2016rshah/githubchart-api#7]
I'm using this for a website and noticed it usually takes a couple seconds for the image to load. Is there any chance you can add the `Cache-Control` header so a user's browser will cache the image for some reasonable amount of time (e.g. one day).

I'm assuming it should just be a case of adding the following around line 26 of `app.rb`.
```ruby
headers 'Cache-Control' => 'max-age=86400'
```

**Comment by 2016rshah** [comment]
Hell yeah that would be awesome! Send in a PR, please

**Comment by Michael-F-Bryan** [comment]
Done (#8). Once this is merged would you be able to update the website to the latest version?
